# Generated by Django 4.1.5 on 2023-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='slug_hash',
            field=models.CharField(default='', max_length=8),
        ),
    ]
