# Generated by Django 4.1.5 on 2023-01-17 09:48

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_slug_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default=members.models.today),
        ),
        migrations.AlterField(
            model_name='member',
            name='slug_hash',
            field=models.CharField(default=members.models.generate_slug_hash, max_length=8),
        ),
    ]
